### ISSUE TITLE
Reveal latte deprecated?

### ISSUE THREAD

**Issue by lulco** [revealphp/reveal-src#27]
Hi, did you deprecate [reveal-latte](https://github.com/deprecated-packages/reveal-latte)?

**Comment by TomasVotruba** [comment]
Hi, yes. The package is released a whole in https://github.com/revealphp/reveal

That way is downgraded to PHP 7.2 and can be used on older project:
https://github.com/revealphp/reveal-src/commit/f811e15a4271550f13f2861b8ea42f3091747ee6
