### ISSUE TITLE
Scoper

### ISSUE THREAD

**Issue by lulco** [revealphp/reveal-src#29]
Symplify classes probably shouldn't be prefixed. I've got several errors like `Service of type RevealPrefix20220606\Symplify... not found. Did you add it to configuration file?`
But also `Service of type Reveal\LattePHPStanCompiler\LatteToPhpCompiler: Service of type RevealPrefix20220606\Latte\Parser required by $latteParser in LatteToPhpCompiler::__construct() not found. Did you add it to configuration file?`

All classes used as services should stay with original names, right?

I can try to prepare PR to scoper.php. It's about adding some exclude-namespaces isn't it?

**Comment by TomasVotruba** [comment]
Only the Symplify classes that are part of public API should not be prefixed. Otherwise, yes. What such classes do you use?

Possibly related to https://github.com/revealphp/reveal/issues/3
